/*
 * DIO_Cfg.h
 *
 *  Created on: Sep 9, 2023
 *      Author: abdelrahmanhossam
 */

#ifndef INCLUDE_MCAL_DIO_DIO_CFG_H_
#define INCLUDE_MCAL_DIO_DIO_CFG_H_

#define PIN_INPUT 	0
#define PIN_OUTPUT	1

#define PA0_INITIAL_DIRECTION	PIN_INPUT
#define PA1_INITIAL_DIRECTION	PIN_INPUT
#define PA2_INITIAL_DIRECTION	PIN_INPUT
#define PA3_INITIAL_DIRECTION	PIN_INPUT
#define PA4_INITIAL_DIRECTION	PIN_INPUT
#define PA5_INITIAL_DIRECTION	PIN_INPUT
#define PA6_INITIAL_DIRECTION	PIN_INPUT
#define PA7_INITIAL_DIRECTION	PIN_INPUT

#define PB0_INITIAL_DIRECTION	PIN_INPUT
#define PB1_INITIAL_DIRECTION	PIN_INPUT
#define PB2_INITIAL_DIRECTION	PIN_INPUT
#define PB3_INITIAL_DIRECTION	PIN_INPUT
#define PB4_INITIAL_DIRECTION	PIN_INPUT
#define PB5_INITIAL_DIRECTION	PIN_INPUT
#define PB6_INITIAL_DIRECTION	PIN_INPUT
#define PB7_INITIAL_DIRECTION	PIN_INPUT

#define PC0_INITIAL_DIRECTION	PIN_INPUT
#define PC1_INITIAL_DIRECTION	PIN_INPUT
#define PC2_INITIAL_DIRECTION	PIN_INPUT
#define PC3_INITIAL_DIRECTION	PIN_INPUT
#define PC4_INITIAL_DIRECTION	PIN_INPUT
#define PC5_INITIAL_DIRECTION	PIN_INPUT
#define PC6_INITIAL_DIRECTION	PIN_INPUT
#define PC7_INITIAL_DIRECTION	PIN_INPUT

#define PD0_INITIAL_DIRECTION	PIN_INPUT
#define PD1_INITIAL_DIRECTION	PIN_INPUT
#define PD2_INITIAL_DIRECTION	PIN_INPUT
#define PD3_INITIAL_DIRECTION	PIN_INPUT
#define PD4_INITIAL_DIRECTION	PIN_INPUT
#define PD5_INITIAL_DIRECTION	PIN_INPUT
#define PD6_INITIAL_DIRECTION	PIN_INPUT
#define PD7_INITIAL_DIRECTION	PIN_INPUT

/**********************************************************/
#define PIN_FLOATING 	0
#define PIN_PULLUP  	1

#define PIN_RESET		0
#define PIN_SET		    1

#define PA0_INITIAL_VALUE	PIN_FLOATING
#define PA1_INITIAL_VALUE	PIN_FLOATING
#define PA2_INITIAL_VALUE	PIN_FLOATING
#define PA3_INITIAL_VALUE	PIN_FLOATING
#define PA4_INITIAL_VALUE	PIN_FLOATING
#define PA5_INITIAL_VALUE	PIN_FLOATING
#define PA6_INITIAL_VALUE	PIN_FLOATING
#define PA7_INITIAL_VALUE	PIN_FLOATING

#define PB0_INITIAL_VALUE	PIN_FLOATING
#define PB1_INITIAL_VALUE	PIN_FLOATING
#define PB2_INITIAL_VALUE	PIN_FLOATING
#define PB3_INITIAL_VALUE	PIN_FLOATING
#define PB4_INITIAL_VALUE	PIN_FLOATING
#define PB5_INITIAL_VALUE	PIN_FLOATING
#define PB6_INITIAL_VALUE	PIN_FLOATING
#define PB7_INITIAL_VALUE	PIN_FLOATING

#define PC0_INITIAL_VALUE	PIN_FLOATING
#define PC1_INITIAL_VALUE	PIN_FLOATING
#define PC2_INITIAL_VALUE	PIN_FLOATING
#define PC3_INITIAL_VALUE	PIN_FLOATING
#define PC4_INITIAL_VALUE	PIN_FLOATING
#define PC5_INITIAL_VALUE	PIN_FLOATING
#define PC6_INITIAL_VALUE	PIN_FLOATING
#define PC7_INITIAL_VALUE	PIN_FLOATING

#define PD0_INITIAL_VALUE	PIN_FLOATING
#define PD1_INITIAL_VALUE	PIN_FLOATING
#define PD2_INITIAL_VALUE	PIN_FLOATING
#define PD3_INITIAL_VALUE	PIN_FLOATING
#define PD4_INITIAL_VALUE	PIN_FLOATING
#define PD5_INITIAL_VALUE	PIN_FLOATING
#define PD6_INITIAL_VALUE	PIN_FLOATING
#define PD7_INITIAL_VALUE	PIN_FLOATING


#endif /* INCLUDE_MCAL_DIO_DIO_CFG_H_ */
