/*
 * LCD_Private.h
 *
 *  Created on: Sep 15, 2023
 *      Author: abdelrahmanhossam
 */

#ifndef INCLUDE_HAL_LCD_LCD_PRIVATE_H_
#define INCLUDE_HAL_LCD_LCD_PRIVATE_H_


#define DONOT_CARE_BIT 0

#define FUNCTION_SET CONC_BIT(0,0,1,1,LCD_NO_LINES,LCD_CHAR_FONT,DONOT_CARE_BIT,DONOT_CARE_BIT)

#define DISPLAY_ON_OFF CONC_BIT(0,0,0,0,1,LCD_DISPLAY_ON_OFF,LCD_CURSOR_DISPLAY,LCD_CURSOR_BLINK)

#define DISPLAY_CLEAR 0x01

#define ENTRY_MODE_SET CONC_BIT(0,0,0,0,0,1,LCD_MOVE_DIRECTION,LCD_SHIFT)

#endif /* INCLUDE_HAL_LCD_LCD_PRIVATE_H_ */
