/*
 * DIO_Cfg.h
 *
 *  Created on: Sep 8, 2023
 *      Author: abdelrahmanhossam
 */

#ifndef INCLUDE_MCAL_DIO_DIO_CFG_H_
#define INCLUDE_MCAL_DIO_DIO_CFG_H_

#define PIN_INPUT  0
#define PIN_OUTPUT 1

#define PA0_INITIAL_DIRECTION 	PIN_OUTPUT
#define PA1_INITIAL_DIRECTION 	PIN_INPUT
#define PA2_INITIAL_DIRECTION 	PIN_INPUT
#define PA3_INITIAL_DIRECTION 	PIN_INPUT
#define PA4_INITIAL_DIRECTION 	PIN_INPUT
#define PA5_INITIAL_DIRECTION 	PIN_INPUT
#define PA6_INITIAL_DIRECTION 	PIN_INPUT
#define PA7_INITIAL_DIRECTION 	PIN_INPUT

#define PB0_INITIAL_DIRECTION 	PIN_INPUT
#define PB1_INITIAL_DIRECTION 	PIN_INPUT
#define PB2_INITIAL_DIRECTION 	PIN_INPUT
#define PB3_INITIAL_DIRECTION 	PIN_OUTPUT
#define PB4_INITIAL_DIRECTION 	PIN_INPUT
#define PB5_INITIAL_DIRECTION 	PIN_INPUT
#define PB6_INITIAL_DIRECTION 	PIN_INPUT
#define PB7_INITIAL_DIRECTION 	PIN_INPUT

#define PC0_INITIAL_DIRECTION 	PIN_OUTPUT
#define PC1_INITIAL_DIRECTION 	PIN_OUTPUT
#define PC2_INITIAL_DIRECTION 	PIN_OUTPUT
#define PC3_INITIAL_DIRECTION 	PIN_OUTPUT
#define PC4_INITIAL_DIRECTION 	PIN_OUTPUT
#define PC5_INITIAL_DIRECTION 	PIN_OUTPUT
#define PC6_INITIAL_DIRECTION 	PIN_OUTPUT
#define PC7_INITIAL_DIRECTION 	PIN_OUTPUT

#define PD0_INITIAL_DIRECTION 	PIN_OUTPUT
#define PD1_INITIAL_DIRECTION 	PIN_OUTPUT
#define PD2_INITIAL_DIRECTION 	PIN_INPUT
#define PD3_INITIAL_DIRECTION 	PIN_OUTPUT
#define PD4_INITIAL_DIRECTION 	PIN_OUTPUT
#define PD5_INITIAL_DIRECTION 	PIN_OUTPUT
#define PD6_INITIAL_DIRECTION 	PIN_OUTPUT
#define PD7_INITIAL_DIRECTION 	PIN_OUTPUT

/*************************************************************************/
/*************************************************************************/
/*************************************************************************/
/*************************************************************************/

#define PIN_FLOATING  0
#define PIN_PULLUP    1

#define PIN_HIGH      1
#define PIN_LOW       0


#define PA0_INITIAL_VALUE 		PIN_LOW
#define PA1_INITIAL_VALUE 		PIN_FLOATING
#define PA2_INITIAL_VALUE 		PIN_FLOATING
#define PA3_INITIAL_VALUE 		PIN_FLOATING
#define PA4_INITIAL_VALUE 		PIN_FLOATING
#define PA5_INITIAL_VALUE 		PIN_FLOATING
#define PA6_INITIAL_VALUE 		PIN_FLOATING
#define PA7_INITIAL_VALUE 		PIN_FLOATING

#define PB0_INITIAL_VALUE 		PIN_FLOATING
#define PB1_INITIAL_VALUE 		PIN_FLOATING
#define PB2_INITIAL_VALUE 		PIN_FLOATING
#define PB3_INITIAL_VALUE 		PIN_LOW
#define PB4_INITIAL_VALUE 		PIN_FLOATING
#define PB5_INITIAL_VALUE 		PIN_FLOATING
#define PB6_INITIAL_VALUE 		PIN_FLOATING
#define PB7_INITIAL_VALUE 		PIN_FLOATING

#define PC0_INITIAL_VALUE 		PIN_LOW
#define PC1_INITIAL_VALUE 		PIN_LOW
#define PC2_INITIAL_VALUE 		PIN_LOW
#define PC3_INITIAL_VALUE 		PIN_LOW
#define PC4_INITIAL_VALUE 		PIN_LOW
#define PC5_INITIAL_VALUE 		PIN_LOW
#define PC6_INITIAL_VALUE 		PIN_LOW
#define PC7_INITIAL_VALUE 		PIN_LOW

#define PD0_INITIAL_VALUE 		PIN_LOW
#define PD1_INITIAL_VALUE 		PIN_LOW
#define PD2_INITIAL_VALUE 		PIN_FLOATING
#define PD3_INITIAL_VALUE 		PIN_LOW
#define PD4_INITIAL_VALUE 		PIN_LOW
#define PD5_INITIAL_VALUE 		PIN_LOW
#define PD6_INITIAL_VALUE 		PIN_LOW
#define PD7_INITIAL_VALUE 		PIN_LOW

#endif /* INCLUDE_MCAL_DIO_DIO_CFG_H_ */
